### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by stefangal** [stefangal/DicePrediction#1]
**TODO:**

- [ ] Code the function to roll x-times the dice with random results
- [ ] Use matplotlib to visualise how many times each of the results [1-6] were rolled
- [ ] Use Scikit-Learn to predict next rolls and see the prediction accuracy
